/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBG: typeof import('./src/components/AppBG.vue')['default']
    AppEditor: typeof import('./src/components/AppEditor.vue')['default']
    AppUpload: typeof import('./src/components/AppUpload.vue')['default']
  }
}
